[CompetitionServer]
    port = 65335
    timeout = 10
    log = "DEBUG"
    game_path = "examples/simple/game.py"
    game_class = "ExampleGame"
    game_db_path = "simple_games.db"
    game_db_name = "data"
    user_db_path = "simple_users.db"
    user_db_name = "data"
    match_quality_threshold = 0.8
    percentage_min_players_waiting = 0.1
    percental_time_bonus = 0.1
