[CompetitionServer]
    port = 65335
    timeout = 10
    log = "DEBUG"
    game_path = "examples/rockpaperscissors/game.py"
    game_class = "RPSGame"
    database_path = "RPS.db"
    match_quality_threshold = 0.8
    percentage_min_players_waiting = 0.1
    percental_time_bonus = 0.1
